//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.DbService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DepoDbEntities : DbContext
    {
        public DepoDbEntities()
            : base("name=DepoDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_cari_tur> tbl_cari_tur { get; set; }
        public virtual DbSet<tbl_depo> tbl_depo { get; set; }
        public virtual DbSet<tbl_fatura> tbl_fatura { get; set; }
        public virtual DbSet<tbl_fatura_detay> tbl_fatura_detay { get; set; }
        public virtual DbSet<tbl_fatura_tip> tbl_fatura_tip { get; set; }
        public virtual DbSet<tbl_kullanici> tbl_kullanici { get; set; }
        public virtual DbSet<tbl_kullanici_sube> tbl_kullanici_sube { get; set; }
        public virtual DbSet<tbl_menu> tbl_menu { get; set; }
        public virtual DbSet<tbl_rol> tbl_rol { get; set; }
        public virtual DbSet<tbl_rol_menu> tbl_rol_menu { get; set; }
        public virtual DbSet<tbl_sirket> tbl_sirket { get; set; }
        public virtual DbSet<tbl_sube> tbl_sube { get; set; }
        public virtual DbSet<tbl_urun> tbl_urun { get; set; }
        public virtual DbSet<tbl_urun_birim> tbl_urun_birim { get; set; }
        public virtual DbSet<tbl_urun_kategori> tbl_urun_kategori { get; set; }
        public virtual DbSet<tbl_cari> tbl_cari { get; set; }
    }
}
