//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.DbService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_urun
    {
        public int ID_URUN { get; set; }
        public string URUN_AD { get; set; }
        public string URUN_BARKOD { get; set; }
        public Nullable<int> ID_KATEGORI { get; set; }
        public Nullable<int> URUN_BIRIM { get; set; }
        public Nullable<int> MIKTARI { get; set; }
        public Nullable<double> ALIS_FIYAT { get; set; }
        public Nullable<double> BIRIM_FIYAT { get; set; }
        public Nullable<double> ISKONTO_TUTAR { get; set; }
        public Nullable<double> KDVSIZ_SATIS_FIYAT { get; set; }
        public Nullable<double> KDV_ORANI { get; set; }
        public Nullable<double> KDV_TUTARI { get; set; }
        public Nullable<double> SATIS_FIYATI { get; set; }
        public Nullable<bool> SILINDI { get; set; }
    }
}
