//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.DbService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_fatura_detay
    {
        public int ID_FATURADETAY { get; set; }
        public Nullable<int> ID_FATURA { get; set; }
        public Nullable<double> BIRIM_FIYAT { get; set; }
        public Nullable<double> ISKONTOTUTARI { get; set; }
        public Nullable<double> KDVSIZ_SATIS_FIYATI { get; set; }
        public Nullable<double> KDV_ORANI { get; set; }
        public Nullable<double> KDV_TUTARI { get; set; }
        public Nullable<double> SATIS_FIYAT { get; set; }
        public Nullable<int> MIKTAR { get; set; }
        public Nullable<bool> TOPLAM_TUTAR { get; set; }
        public Nullable<bool> IPTAL { get; set; }
    }
}
