//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.DbService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_urun_kategori
    {
        public int ID_KATEGORI { get; set; }
        public string AD { get; set; }
        public Nullable<int> UST_KATEGORI { get; set; }
        public Nullable<int> ID_SUBE { get; set; }
        public Nullable<int> ID_EKLEYEN_KULLANICI { get; set; }
        public Nullable<System.DateTime> EKLEME_TARHI { get; set; }
        public Nullable<int> ID_DUZENLEYEN { get; set; }
        public Nullable<System.DateTime> DUZENLEME_TARIHI { get; set; }
        public Nullable<bool> SILINDI { get; set; }
    }
}
