//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.DbService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_fatura
    {
        public int ID_FATURA { get; set; }
        public Nullable<int> ID_DEPO { get; set; }
        public Nullable<int> ID_FATURA_TIP { get; set; }
        public Nullable<int> ID_ODEMETUR { get; set; }
        public string FATURA_NO { get; set; }
        public Nullable<int> ID_CARIKART { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<double> TOPLAM_BIRIM_FIYAT { get; set; }
        public Nullable<double> TOPLAM_ISKONTOTUTARI { get; set; }
        public Nullable<double> TOPLAM_KDV_TUTARI { get; set; }
        public Nullable<double> GENEL_ISKONTO_TUTARI { get; set; }
        public Nullable<double> GENEL_ISKONTO_ACIKLAMA { get; set; }
        public Nullable<double> GENEL_TOPLAM { get; set; }
        public Nullable<System.DateTime> KAYIT_TARIHI { get; set; }
        public Nullable<int> ID_EKLEYEN_KULLANICI { get; set; }
        public Nullable<bool> IPTAL { get; set; }
    }
}
