//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.DbService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_fatura_tip
    {
        public int ID_FATURA_TIP { get; set; }
        public string AD { get; set; }
        public Nullable<bool> SILINDI { get; set; }
    }
}
