//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.DbService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_kullanici
    {
        public int ID_KULLANICI { get; set; }
        public string TC_KIMLIK_NO { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string KULLANICI_AD { get; set; }
        public string SIFRE { get; set; }
        public string TEL_NO { get; set; }
        public string E_POSTA { get; set; }
        public string GUVENLIK_CEVABI { get; set; }
        public Nullable<int> ID_ROL { get; set; }
        public Nullable<bool> SILINDI { get; set; }
    }
}
