//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.DbService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cari
    {
        public int ID_CARI { get; set; }
        public Nullable<int> ID_CARI_TUR { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string TC_KIMLIK_NO { get; set; }
        public string TEL_NO { get; set; }
        public Nullable<int> EKLEYEN_KULLANICI { get; set; }
        public Nullable<System.DateTime> EKLEME_TARIHI { get; set; }
        public Nullable<int> ID_DUZENLEYEN { get; set; }
        public string E_POSTA { get; set; }
        public Nullable<System.DateTime> DUZENLEME_TARIHI { get; set; }
        public Nullable<bool> SILINDI { get; set; }
    }
}
