//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.DbService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cari_tur
    {
        public int ID_CARI_TUR { get; set; }
        public string AD { get; set; }
    }
}
