//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.DbService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_rol_menu
    {
        public int ID { get; set; }
        public Nullable<int> ID_MENU { get; set; }
        public Nullable<int> ID_ROL { get; set; }
    }
}
